<?php
/**
* @var \Ecommage\Blogext3\Block\Blog\Form $block
* @var
*/
$url =  $block->getUrl('ecommage_blogext3/index/save');
$title = $block->getTitle();
?>
<h1><?php echo $title; ?></h1>
<form id="send-order-email" action="<?php echo $url; ?>" method="post">
    <div class="form-group">
        <label>Email Address</label>
        <input type="text" class="input-text" id="email" class="form-control" name="email">
    </div>
    <button type="submit" class="mt-2">Send Email</button>
</form>
