<?php
/**
 * @var Ecommage\Blogext3\Block\Blog\TestArgument $block;
 */
var_dump($block->getDataHelper());

$argument = $block->getArgument();
$data1 = $block->getArgument();
$data2 = $block->getArgument1();
$data3 = $block->getArgument2();
?>
<!--<h1>--><?php //echo "Tham so duoc truyen vao la :" . $data1; ?><!--</h1>-->
<h1><?php echo "Tham so duoc truyen vao la : " . $data2; ?></h1>
<h1><?php echo "Tham so duoc truyen vao la : " . $data3; ?></h1>
